//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CargoTransport1.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        public int Acc_ID { get; set; }
        public string Acc_Login { get; set; }
        public string Acc_Password { get; set; }
    }
}
