//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CargoTransport1.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Ord_ID { get; set; }
        public int Cl_ID { get; set; }
        public int Del_ID { get; set; }
        public Nullable<System.DateTime> Ord_DateStart { get; set; }
        public Nullable<System.DateTime> Ord_DateEnd { get; set; }
        public string Ord_PlaceStart { get; set; }
        public string Ord_PlaceEnd { get; set; }
        public Nullable<decimal> Ord_Price { get; set; }
        public Nullable<decimal> Distance { get; set; }
        public string Package { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Deliveries Deliveries { get; set; }
    }
}
